### ISSUE TITLE
Watching should only rebuild necessary files

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/Snippets#4]
This would be a bit of work, but it'd be nice if changing a single template didn't regenerate every page if it didn't need to. However, doing this right might be more work than is worth for a simple script.

**Comment by bromagosa** [comment]
Yep, I considered this but it's quite a lot of work that involves grepping every page in search for the affected templates. It turns out it's not so simple, and after all building the whole thing -even in big pages like the Snap<i>!</i> site- takes just a couple of seconds, so it's not really worth it IMO.

**Comment by bromagosa** [comment]
Also, imagine the change is in a static file or an `include`d template. This would mean you need to grep not only pages but also templates. A change in an image file referenced in the footer would mean having to traverse the whole structure.

**Comment by cycomachead** [comment]
Building has felt a little slow to me, but mostly the output of seeing which pages change when you make a change would be useful. 

If you change the footer you can't help but rebuild all pages. But lots of times you don't change something global, or you just want a static JS file to be copied over. 

Anyway, I was imaging that a nice way to do build the list of pages is to build a graph as you parse the site, then the dependency resolution isn't as complex. Though I really don't know bash well enough to do that...
